name: design_tokens
description: Package containing design token files
version: 0.0.1

environment:
  sdk: ">=2.12.0 <4.0.0"

# This part is important - specifies this is a Flutter package
flutter:
  # Include token files in the assets section
  assets:
    - packages/core-tokens/json/color-palette.json
    - packages/webos-tokens/json/color-brand.json
    - packages/webos-tokens/json/alias.json
    - packages/webos-tokens/json/border-radius.json
    - packages/webos-tokens/json/font-size.json
    - packages/webos-tokens/json/font-weight.json
    - packages/webos-tokens/json/spacing.json
    
